### PR TITLE
Add icons for HM-Sec-SC-2, HM-LC-RGBW-WM and HM-Sen-MDIR-WM55.

### PR DESCRIPTION
**Pull request by angelnu**

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Missing images itself: 
- 111_hm-lc-rgbw-wm_thumb.png
- 103_hm-sen-mdir-wm55_thumb.png'

**Comment by angelnu** [comment]
Sorry Bluefox - added now

**Comment by Apollon77** [comment]
I checked my logs and find two more: HM-Dis-WM55 and HM-ES-PMSw1-DR ... maybe you can add them too ? ;-))

**Comment by angelnu** [comment]
There seem to be more than those missing icons. I found the icons bellow present in my CCU and not in the iobroker adapter.

I can add them all but I do not know exactly what is type they report (hm-rpc.js). I can guess the names apart from the case...

Should I commit the pngs for now?

84_hm-rc-4-x_thumb.png
92_hm-ou-cm-pcb_thumb.png
94_hm-mod-re-8_thumb.png
95_group_hm-cc-vg-1_thumb.png
96_hm-tc-it-wm-w-eu_thumb.png
97_hm-dis-wm55_thumb.png
99_hm-mod-em-8_thumb.png
100_hm-rc-8_thumb.png
101_hm-sen-db-pcb_thumb.png
102_hm-es-tx-wm_thumb.png
104_hm-sec-sd-2_thumb.png
105_hm-sec-sd-2-team_thumb.png
107_hm-es-pmsw1-pl-R2_thumb.png
107_hm-es-pmsw1-pl-R3_thumb.png
107_hm-es-pmsw1-pl-R4_thumb.png
107_hm-es-pmsw1-pl-R5_thumb.png
108_hm-rc-dis-h-x-eu_thump.png
109_hm-lc-sw1-pl-ct_thump.png
110_hm-es-pmsw1-dr_thump.png
112_hmip-wrc2_thumb.png
113_hmip-psm_thumb.png
114_hm-lc-dim1t-fm-lf_thumb.png
114_hm-lc-dim1t-fm-lf_thumb_2.png
114_hm-lc-dim1t-fm-lf_thumb_3.png
115_hm-es-pmsw1-sm_thumb.png

**Comment by angelnu** [comment]
Ok, I found the Database in the CCU with the mapping. Working in the fix...

**Comment by Apollon77** [comment]
you are great !

**Comment by angelnu** [comment]
there are some devices I did not find the Type so I put them commented out.

**Comment by GermanBluefox** [comment]
Now it is very good. Thank you!

**Pull request merged**
