### PR TITLE
Update hm-rpc.js

### PR DESCRIPTION
**Pull request by Zefau**

### CODE REVIEW

**Comment by Apollon77** [comment]
And where are the needed Admin changes to also configure this?

**Comment by GermanBluefox** [comment]
I am missing changes of io-package.json in native part.

**Comment by GermanBluefox** [comment]
I don't know, why you closed the PR, but I suggest you to finish this task.

**Comment by Zefau** [comment]
See https://github.com/ioBroker/ioBroker.hm-rpc/issues/94#issuecomment-423770757.

**Pull request closed without merging**
