### PR TITLE
(BuZZy1337) added metas for missing devices

### PR DESCRIPTION
**Pull request by BuZZy1337**
Regarding https://github.com/ioBroker/ioBroker.hm-rpc/issues/71 and https://github.com/ioBroker/ioBroker.hm-rpc/issues/70

### CODE REVIEW

**Comment by Apollon77** [comment]
Can you please also increase version numbers and add in README ... then I can release very fast to npm :-)
Or maybe ask in forum for more devices and do one bit "hmip" patch?! :-)

**Comment by BuZZy1337** [comment]
The problem about asking the users to send some informations about HM-Ip Metas is, that the log message only appears one time at the first sync of the new device.
So everybody would have to delete the stuff which was automatically created during first sync, sync all devices again and then send the informations..
I do not want to expect that from all users.. :smile:

**Comment by BuZZy1337** [comment]
Bump version to 1.6.2 -> Done! :relaxed:

**Comment by Apollon77** [comment]
published

**Pull request merged**
