### PR TITLE
Added Metas for HM-Sen-MDIR-O-3

### PR DESCRIPTION
**Pull request by BuZZy1337**
Regarding https://github.com/ioBroker/ioBroker.hm-rpc/issues/79

### CODE REVIEW

**Comment by Apollon77** [comment]
Can you please also increase Version and add info to readme. Then we can go directly to release ;-)

**Comment by BuZZy1337** [comment]
Done. ☺️

**Comment by Apollon77** [comment]
Perfect, thank you!

**Comment by Apollon77** [comment]
published to npm

**Pull request merged**
